FROM amazonlinux:latest

WORKDIR /app

COPY requirements.txt /app

COPY model_save.py /app

RUN yum update -y

RUN yum install -y python3

RUN yum install -y python3-pip

RUN pip3 install --no-cache-dir -r requirements.txt

RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu